library app_config;
//Criando variavel global, dai altero ela la no settingsPage
bool darkMode = false;


String currentLanguageCode = 'pt'; // ou 'en'
Map<String, Map<String, String>> translations = {
  'pt': {
    'add': 'Adicionar',
    'no_pets': 'Nenhum pet cadastrado.',
    'name': 'Nome:',
    'age': 'Idade:',
    'breed': 'Raça',
    'gender_male': 'Sexo: Macho',
    'gender_female': 'Sexo: Fêmea',
    'size_small': 'Porte: Pequeno',
    'size_medium': 'Porte: Médio',
    'size_large': 'Porte: Grande',
    'pet_updated': 'Pet atualizado com sucesso!',
    'pet_saved': 'Pet salvo com sucesso!',
    'fill_all_fields': 'Todos os campos precisam ser preenchidos para salvar!',
    'small_size': 'Pequeno porte',
    'medium_size': 'Médio porte',
    'large_size': 'Grande porte',
    'female': 'Fêmea',
    'male': 'Macho',
    'breed_hint': 'Raça do animal',
    'age_hint': 'Idade',
    'name_hint': 'Nome do pet',
    'no_image': 'No Image Picked',
    'language': 'Linguagem:',
    'dark_mode': 'Modo escuro:',
    'settings': 'Configurações',
    'pt': 'Português',
    'en': 'Inglês',
  },
  'en': {
    'add': 'Add',
    'no_pets': 'No pets registered.',
    'name': 'Name:',
    'age': 'Age:',
    'breed': 'Breed',
    'gender_male': 'Gender: Male',
    'gender_female': 'Gender: Female',
    'size_small': 'Size: Small',
    'size_medium': 'Size: Medium',
    'size_large': 'Size: Large',
    'pet_updated': 'Pet updated successfully!',
    'pet_saved': 'Pet saved successfully!',
    'fill_all_fields': 'All fields must be filled in to save!',
    'small_size': 'Small size',
    'medium_size': 'Medium size',
    'large_size': 'Large size',
    'female': 'Female',
    'male': 'Male',
    'breed_hint': 'Animal breed',
    'age_hint': 'Age',
    'name_hint': 'Pet name',
    'no_image': 'No Image Picked',
    'language': 'Language:',
    'dark_mode': 'Dark mode:',
    'settings': 'Settings',
    'pt': 'Portuguese',
    'en': 'English',
  }
};